name: build
on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  goBuild:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: tidy
        run: | 
            go clean -modcache
            go mod tidy
      - name: server build
        run: go build server/main.go
      - name: client build
        run: |
            cd client
            make build-all
        