name: server

on:
  push:
    branches: [ "ga_trial" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'

      - name: install golang cli
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: check installation and lint
        run: |
         go mod tidy
         cd client
         make build-all

      #- name: Lint
       # run:  ./check.sh
      #- name: Test
       # run: go test -v ./...