name: Lint 

on:
  push:
    branches: [ "ga_trial" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'

      - name: client build
        run: |
         cd client
         make build-all
      #- name: Lint
       # run:  ./check.sh
      #- name: Test
       # run: go test -v ./...